package capability1;

/*
	* Exercise 7: Fibonacci number
		* Write a method that returns the sum of all even Fibonacci numbers. Consider all
		* Fibonacci numbers that are less than or equal to n.
		* Each new element in the Fibonacci sequence is generated by adding the previous two
		* elements.
		* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, etc.
		* public static int evenFibonacciSum(Integer n){}
 */

import java.util.Scanner;

public class evenFibanocci {
	
	int f1 = 0, f2 = 1, fn, n, sum = 0;

	public static void main(String[] args) {
		
		Scanner in = new Scanner(System.in);
		evenFibanocci ef = new evenFibanocci();
		System.out.println("Enter a positive number: ");
		ef.n = in.nextInt();
		int result = ef.evenFibonacciSum(ef.n);
		
		System.out.println("Sum = " + result);
		

	}

	public int evenFibonacciSum(int n) {
		do {
			fn = f1 + f2;
			
			if(fn%2 == 0) { 
				sum = sum + fn; 
			}
			f1 = f2;
			f2 = fn;
		} while(fn < n);
		
			if(fn%2 == 0) {
				sum = sum - fn;
				return sum;
			} else {
				return sum;
			}
		}
	}

